RestDemo/RestDemo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('snippets.urls')),
    path('mq/', include('mq.urls')),
    path('polls/', include('polls.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

RestDemo/mq/urls.py
from django.urls import path
from . import views

app_name = 'mq'

urlpatterns = [
    path('', views.index, name='index'),
    # ex: /mq/5/
    path('<int:id>/', views.detail, name='detail'),
    # ex: /mq/5/send
    path('<int:id>/send/', views.send, name='send'),
]

RestDemo/mq/models.py
from django.db import models


class MQChannel(models.Model):
    MQCHANNEL_TYPE = (
       ('queue', ('Point to Point model')),
       ('topic', ('Pub Sub model'))
    )
    id = models.AutoField(primary_key=True)
    mqchannel_name = models.CharField(max_length=20)
    mqchannel_type = models.CharField(
        choices=MQCHANNEL_TYPE, 
        default='queue', 
        max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ('created', )
        db_table = u'"restdemo\".\"mqchannel"'
    def __str__(self):
        return self.mqchannel_name
    

        
class MQMessage(models.Model):
    MESSAGE_TYPE = (
       ('text/plain', ('text/plain')),
       ('application/xml', ('application/xml')),
       ('application/json',('application/json')),
       #('text/html', _('text/html')),
       #('image/gif', _('image/gif')),
       #('image/jpeg', _('image/jpeg')),
    )
    id = models.AutoField(primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    message_text = models.CharField(max_length=500)    
    message_type = models.CharField(
       max_length=100,
       choices=MESSAGE_TYPE,
       default='text/plain',
    )
    mqchannel_id = models.ForeignKey(MQChannel, on_delete=models.CASCADE)
    class Meta:
        ordering = ('created', )
        db_table = u'"restdemo\".\"mqmessage"'
    
    def __str__(self):
        return self.message_text
        

RestDemo/mq/views.py
from django.shortcuts import get_object_or_404, render
from .models import MQChannel

from mq_events.send_receive import SendReceiveAPI
from django.http import HttpResponseRedirect
from django.urls import reverse

#def mqchannels(request):
    #return HttpResponse("You're at the mqchannels index. You can access the following MQ Channels: ")
# Create your views here.

def index(request):
    mqchannel_list = MQChannel.objects.order_by('created')
    context = {'mqchannel_list': mqchannel_list}
    return render(request, 'mq/index.html', context)

def detail(request, id):
    mqchannel = get_object_or_404(MQChannel, pk=id)
    mq_channel = SendReceiveAPI().subscribe_mqchannel(mqchannel)    
    return render(request, 'mq/detail.html', {'mqchannel': mq_channel})

def send(request, id):
    input_message = request.POST.get('message', 'fake message input text')
    
    print("input message = " + input_message)
    print("channel_id = " + str(id))
    mqchannel = get_object_or_404(MQChannel, pk=id)
    SendReceiveAPI().send_mqchannel(mqchannel, input_message)
    #mqchannel_list = MQChannel.objects.order_by('created')
    #context = {'mqchannel_list': mqchannel_list}
    return HttpResponseRedirect(reverse('mq:index')) 

RestDemo/mq/templates/mq/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MQ Channel Messages page</title>
    <link rel = "stylesheet"
    		type = "text/css"
   			href = "/static/mq/base.css" />
  </head>
  <body>
  <form action="{% url 'mq:send' mqchannel.id %}" method="post">
    {% csrf_token %}
    <input type="text" name="message" id="{{ mqchannel.id }}" value="Default message text">
    <input type="submit" value="Send">
    
    <table border="2">
      <tr>
         <th border="1">Messages posted in mqchannel <a href="{% url 'mq:index'  %}">{{ mqchannel.mqchannel_name|upper }}</a>
            
   
		</th>
      </tr>
    <ul>

	{% for message in mqchannel.mqmessage_set.all %}
	<tr>
		<td>
			<li>{{ message.message_text|upper }}</li>
		</td>
	</tr>	    
    {% endfor %}
	</ul>
	</table> 
	</form>
  </body>
</html>

RestDemo/mq/templates/mq/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MQChannel Index page</title>
        <link rel = "stylesheet"
    		type = "text/css"
   			href = "/static/mq/base.css" />
  </head>
  <body>
  
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


  
  
  	<table border="1">
	{% if mqchannel_list %}
		
	    <ul>
	    <tr>
	      <th> mqchannel id </th>
	      <th> mqchannel name </th>
	      <th> mqchannel type</th>
	    </tr>
	    {% for mqchannel in mqchannel_list %}
	    <tr>
			<td>
	        	{{ mqchannel.id }}
	        </td>
	        <td>
	        	<a href="{% url 'mq:detail' mqchannel.id %}">{{ mqchannel.mqchannel_name }}</a>
	        </td>
	        <td>
	        	{{ mqchannel.mqchannel_type }}
	        </td>

	     </tr>
	    {% endfor %}
	    </ul>
	    
	</table>
	{% else %}
	    <p>No MQ Channels are available.</p>
	{% endif %}

 </body>
</html>